version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      target: runner
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_STRAPI_URL: http://strapi:1337
      NEXT_PUBLIC_STRAPI_ASSETS_URL: ${NEXT_PUBLIC_STRAPI_ASSETS_URL}
      STRAPI_API_TOKEN: ${STRAPI_API_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    depends_on:
      - strapi
    ports:
      - "9000:3000"
    restart: unless-stopped

  strapi:
    build:
      context: .
      dockerfile: Dockerfile.strapi
      target: runner
    env_file:
      - ./strapi/.env
    environment:
      NODE_ENV: production
      PUBLIC_URL: ${STRAPI_PUBLIC_URL}
    ports:
      - "1337:1337"
    restart: unless-stopped
