# --- deps stage ---
FROM node:20-alpine AS deps
WORKDIR /app

COPY ./strapi/package*.json ./
RUN npm install --omit=dev

# --- build stage ---
FROM node:20-alpine AS build
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY ./strapi ./
ENV NODE_ENV=production
RUN npm run build

# --- runner stage ---
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app ./
EXPOSE 1337
CMD ["npm", "run", "start"]
